"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer/footer";
import { usePathname } from "next/navigation";
import { metadata } from "./metadata"; // Import metadata


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Trimpa",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // Define routes where the header should be hidden
  const hideHeaderRoutes = ["/select-seat"];

  // Determine if the header should be hidden
  const shouldHideHeader = hideHeaderRoutes.includes(pathname);

  return (
    <html lang="en">
              <title>{metadata.title}</title>

      <body className={inter.className}>
        {!shouldHideHeader && <Header />}
        {children}
        {!shouldHideHeader && <Footer />}
        
      </body>
    </html>
  );
}
